# --- Tambahan import di atas ---
from reportlab.pdfgen import canvas
from PyPDF2 import PdfReader, PdfWriter  # opsional, hanya jika pakai overlay background


# -------------------- PDF builder: Exact Layout ala contoh --------------------
def build_spj_pdf_exact(AK: Dict[str, Optional[str]], LQ: Dict[str, int],
                        overlay_template_bytes: Optional[bytes] = None) -> bytes:
    """
    Bangun PDF SPJ dengan layout yang dibuat 'semirip mungkin' dengan contoh.
    Jika overlay_template_bytes diberikan (PDF 1 halaman), gunakan sebagai background.
    Nilai yang dipakai:
      *A: ATAS NAMA (employee)
      *B: TEMPAT ASAL
      *C: TUJUAN
      *D: TGL BERANGKAT (text)
      *E: TGL KEMBALI (text)
      *K: REALISASI HARIAN (nominal daily allowance total)
      *L..*P: Lain-lain (bensin, hotel[CTM], toll, transportasi, parkir)
      *Q: total semua lain-lain (kembali ke karyawan)
      *H: Nama pejabat (kiri) - disesuaikan (Mengetahui)
      *A: Nama pelaksana (kanan)
    """
    # -------- ambil nilai A–Q --------
    A = AK.get("A") or ""
    B = AK.get("B") or ""
    C = AK.get("C") or ""
    D = AK.get("D") or ""
    E = AK.get("E") or ""
    G = AK.get("G") or ""
    H = AK.get("H") or ""     # Mengetahui (kiri)
    I = AK.get("I") or ""     # (jika ingin ditampilkan di bawah kiri/kolom tengah)
    K_txt = AK.get("K") or "IDR 0"

    # Nominal -> angka
    def idr_to_int(s: str) -> int:
        digits = "".join(ch for ch in str(s) if ch.isdigit())
        return int(digits) if digits else 0

    K_val = idr_to_int(K_txt)
    L_val = int(LQ.get("L", 0))
    M_val = int(LQ.get("M", 0))
    N_val = int(LQ.get("N", 0))
    O_val = int(LQ.get("O", 0))
    P_val = int(LQ.get("P", 0))
    Q_val = int(LQ.get("Q", 0))

    # Hitung jumlah hari inklusif dari teks D, E (kalau bisa diparse)
    def parse_date_or_none(s: str) -> Optional[datetime]:
        for fmt in ("%d %B, %Y", "%d %b, %Y", "%d %B %Y", "%d %b %Y", "%d/%B/%Y", "%d/%b/%Y"):
            try:
                return datetime.strptime(s, fmt)
            except Exception:
                continue
        return None

    d_dt = parse_date_or_none(D)
    e_dt = parse_date_or_none(E)
    hari_inclusive = None
    if d_dt and e_dt:
        hari_inclusive = (e_dt.date() - d_dt.date()).days + 1

    # Format IDR (tanpa "Rp." untuk meniru contoh angka yang hanya "2,800,000", nanti kita tambahkan 'Rp.' di tempat yang perlu)
    def fmt_n(n: int) -> str:
        return f"{n:,}".replace(",", ".")

    # ------- Siapkan buffer & ukuran kertas ------
    # Default pakai A4 portrait (mirip contoh)
    PAGE_W, PAGE_H = A4  # ~ (595.28 pt x 841.89 pt)

    # Jika kita pakai overlay_template_bytes (opsional), pastikan ukuran canvas mengikuti ukuran halaman template
    if overlay_template_bytes:
        base_reader = PdfReader(io.BytesIO(overlay_template_bytes))
        page0 = base_reader.pages[0]
        # PyPDF2 pakai koord PDF points
        PAGE_W = float(page0.mediabox.width)
        PAGE_H = float(page0.mediabox.height)

    packet = io.BytesIO()
    c = canvas.Canvas(packet, pagesize=(PAGE_W, PAGE_H))

    # Gaya font dasar
    c.setTitle("SPJ Realisasi Biaya Perjalanan Dinas")
    c.setAuthor("Auto-generated by Streamlit")

    # Util: teks
    def draw_text(x, y, text, size=10, bold=False, align="left"):
        font = "Helvetica-Bold" if bold else "Helvetica"
        c.setFont(font, size)
        if align == "left":
            c.drawString(x, y, text)
        elif align == "center":
            c.drawCentredString(x, y, text)
        elif align == "right":
            c.drawRightString(x, y, text)

    # Util: label+nilai (tiga kolom)
    def draw_row(y, label, value, label_w=120, colon_w=10, val_w=360, size=10, bold_label=False):
        x0 = 40  # margin kiri
        draw_text(x0, y, label, size=size, bold=bold_label)
        draw_text(x0 + label_w, y, ":", size=size)
        draw_text(x0 + label_w + colon_w, y, value, size=size)

    # ====== HEADER (judul form) ======
    # Posisi y dihitung dari bawah; contoh A4 tinggi 842pt. Kita taruh judul di atas tengah.
    draw_text(PAGE_W/2, PAGE_H - 60, "FORMULIR PERHITUNGAN REALISASI BIAYA PERJALANAN DINAS/ PINDAH",
              size=11, bold=True, align="center")

    # ====== BLOK IDENTITAS ======
    y = PAGE_H - 100
    draw_row(y,      "SPPD NO", "")
    y -= 16
    draw_row(y,      "ATAS NAMA", A)         # *A
    y -= 16
    draw_row(y,      "TEMPAT ASAL", B)       # *B
    y -= 16
    draw_row(y,      "TUJUAN", C)            # *C
    y -= 16
    draw_row(y,      "TGL BERANGKAT", D)     # *D
    y -= 16
    draw_row(y,      "TGL KEMBALI", E)       # *E
    y -= 16
    hari_str = str(hari_inclusive) if hari_inclusive is not None else ""
    # JUMLAH HARI: "7   Hari"
    draw_row(y,      "JUMLAH HARI", f"{hari_str}", size=10)
    draw_text(40 + 120 + 10 + 50, y, "Hari", size=10)  # tulisan "Hari" di kolom kanan kecil

    # ====== A. REALISASI BIAYA HARIAN ======
    y -= 28
    draw_text(40, y, "A. REALISASI BIAYA HARIAN:", size=10, bold=True)
    y -= 18
    draw_text(40, y, "PENERIMAAN", size=10)
    y -= 16
    # "Rp." + "HARI TERTULIS SPPD" (di contoh hanya label)
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "HARI TERTULIS SPPD", size=10)

    y -= 16
    draw_text(40, y, "REALISASI", size=10)

    y -= 16
    # "Rp." + *K + "REALISASI HARI"
    draw_text(40, y, "Rp.", size=10)
    draw_text(80, y, f"{fmt_n(K_val)}", size=10)   # *K sebagai angka
    draw_text(180, y, "REALISASI HARI", size=10)

    y -= 16
    # baris jumlah hari lagi (seperti contoh)
    draw_text(40, y, f"{hari_str}", size=10)
    draw_text(60, y, "Hari", size=10)

    y -= 16
    draw_text(40, y, "SELISIH KURANG (kembali ke karyawan)", size=10)

    y -= 16
    draw_text(40, y, "Rp.", size=10)
    draw_text(80, y, f"{fmt_n(K_val)}", size=10)  # *K lagi sesuai contoh
    draw_text(150, y, "(AKOMODASI DITANGGUNG PANITIA)", size=10)

    y -= 16
    draw_text(40, y, "SELISIH TAMBAH (kembali ke perusahaan)", size=10)

    y -= 16
    draw_text(40, y, "Rp.", size=10)
    draw_text(80, y, "-", size=10)

    # ====== B. TRANSPORTASI (PESAWAT) ======
    y -= 24
    draw_text(40, y, "B. REALISASI BIAYA FASILITAS TRANSPORTASI (PESAWAT):", size=10, bold=True)
    y -= 18
    draw_text(40, y, "PENERIMAAN", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10)
    y -= 16
    draw_text(40, y, "REALISASI", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10)
    y -= 16
    draw_text(40, y, "SELISIH KURANG (kembali ke karyawan)", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10)
    y -= 16
    draw_text(40, y, "SELISIH TAMBAH (kembali ke perusahaan)", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10)

    # ====== C. PENGINAPAN ======
    y -= 24
    draw_text(40, y, "C. REALISASI BIAYA PENGINAPAN:", size=10, bold=True)
    y -= 18
    draw_text(40, y, "PENERIMAAN", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10)
    y -= 16
    draw_text(40, y, "REALISASI", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10); draw_text(110, y, "(CTM)", size=10, bold=False)
    y -= 16
    draw_text(40, y, "SELISIH KURANG (kembali ke karyawan)", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10)
    y -= 16
    draw_text(40, y, "SELISIH TAMBAH (kembali ke perusahaan)", size=10)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10)

    # ====== D. JENIS BIAYA LAIN-LAIN ======
    y -= 24
    draw_text(40, y, "D. JENIS BIAYA LAIN-LAIN:", size=10, bold=True)
    y -= 18
    draw_text(40, y, "- REALISASI BENSIN", size=10);        draw_text(220, y, "Rp.", size=10); draw_text(250, y, fmt_n(L_val), size=10)  # *L
    y -= 16
    draw_text(40, y, "- REALISASI HOTEL (CTM)", size=10);    draw_text(220, y, "Rp.", size=10); draw_text(250, y, fmt_n(M_val), size=10)  # *M
    y -= 16
    draw_text(40, y, "- REALISASI TOLL", size=10);           draw_text(220, y, "Rp", size=10);  draw_text(250, y, fmt_n(N_val), size=10)  # *N
    y -= 16
    draw_text(40, y, "- REALISASI TRANSPORTASI", size=10);   draw_text(220, y, "Rp", size=10);  draw_text(250, y, fmt_n(O_val), size=10)  # *O
    y -= 16
    draw_text(40, y, "- REALISASI PARKIR", size=10);         draw_text(220, y, "Rp", size=10);  draw_text(250, y, fmt_n(P_val), size=10)  # *P
    y -= 16
    draw_text(40, y, "SELISIH KURANG (kembali ke karyawan)", size=10)
    y -= 16
    draw_text(40, y, fmt_n(Q_val), size=10)  # *Q (di contoh tampil sendiri sebagai angka)

    # ====== Ringkasan I / II / TOTAL ======
    y -= 24
    draw_text(40, y, "I. TOTAL SELISIH KURANG :", size=10, bold=True)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, fmt_n(Q_val), size=10, bold=True)   # *Q
    y -= 16
    draw_text(40, y, "( total kembali ke karyawan)", size=9)
    y -= 20

    draw_text(40, y, "II. TOTAL SELISIH TAMBAH :", size=10, bold=True)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, "-", size=10, bold=True)
    y -= 16
    draw_text(40, y, "(total kembali ke perusahaan)", size=9)
    y -= 20

    draw_text(40, y, "TOTAL SELISIH :", size=10, bold=True)
    y -= 16
    draw_text(40, y, "Rp.", size=10); draw_text(80, y, fmt_n(Q_val), size=10, bold=True)   # *Q

    # ====== Mengetahui / Tanda Tangan ======
    y -= 40
    draw_text(40, y, "Mengetahui", size=10)
    y -= 18
    # Baris jabatan
    draw_text(40, y, "Pemimpin Unit Kerja/Fungsi", size=10)
    # kolom tengah (mis.: admin/pejabat lain – dari contoh ada 3 kolom). Biarkan kosong/opsional.
    draw_text(PAGE_W/2 - 50, y, "", size=10)
    draw_text(PAGE_W - 220, y, "Pelaksana Perjalanan Dinas", size=10)

    # Garis tanda tangan (opsional): bisa tambahkan line
    y -= 36
    # Nama-nama
    draw_text(40, y, H if H else I, size=10, bold=True)               # *H atau *I (kiri)
    draw_text(PAGE_W/2 - 50, y, "", size=10, bold=True)               # kolom tengah (kosong)
    draw_text(PAGE_W - 220, y, A, size=10, bold=True)                 # *A (kanan)

    # Footnote tanggal & jabatan (opsional, mengambil G di bawah kanan seperti contoh)
    y -= 28
    # Tanggal dikosongkan—contoh menampilkan rentang; kita tampilkan D/E di bawah:
    draw_text(40, y, D, size=10)
    draw_text(180, y, E, size=10)
    y -= 16
    draw_text(40, y, "_Dilarang Mengcopy / Menyebarluaskan Tanpa Izin MR _", size=9)
    y -= 16
    if G:
        draw_text(40, y, G, size=10)

    # Selesai menulis
    c.showPage()
    c.save()
    overlay_pdf = packet.getvalue()

    # === Jika tidak ada template background, langsung pakai overlay_pdf sebagai hasil ===
    if not overlay_template_bytes:
        return overlay_pdf

    # === Mode OVERLAY: gabungkan overlay di atas template background (1 halaman) ===
    base_reader = PdfReader(io.BytesIO(overlay_template_bytes))
    base_page = base_reader.pages[0]

    overlay_reader = PdfReader(io.BytesIO(overlay_pdf))
    overlay_page = overlay_reader.pages[0]

    base_page.merge_page(overlay_page)  # timpa teks A–Q di atas background template

    writer = PdfWriter()
    writer.add_page(base_page)
    out_buf = io.BytesIO()
    writer.write(out_buf)
    return out_buf.getvalue()

